#!/usr/bin/python
#----------------------------------
#  make_dictionary.py
#----------------------------------
#
# builds a dictionary to translate between ints and words

import dictionary

#specify input files  - these are generated by preprocess.py
filename = 'words.txt'
bigram_filename = 'bigrams.txt'

# build the dictionaries
my_dict = dictionary.dictionary([filename],n_vocab=5000)   # build word -> int mapping
bigram_dict = dictionary.dictionary([bigram_filename],n_vocab=5000)   # build bigram -> int mapping

# print the dictionaries
my_dict.print_dictionary_to_file('word_dictionary.txt', True)
bigram_dict.print_dictionary_to_file('bigram_dictionary.txt', True)

#----------------------------------
# translate the file to ints

def translate_file(the_dict,filename):
    ''' translate words in a file to integers, producing an ordered unique list of the words present'''
    infile = open(filename)
    outfile = open(filename + '.int','w')
    for line in infile:
        words = line.split()
        int_list = list(set(dictionary.translate_words_to_integers(words, the_dict.dict)))
        int_list.sort()
        for integer in int_list:
            outfile.write(str(integer) + ' ')
        outfile.write('\n')

#----------------------------------

translate_file(my_dict,filename)
translate_file(bigram_dict,bigram_filename)
